create table item (
                      id int4 generated by default as identity,
                      body varchar(255),
                      brand varchar(255),
                      description varchar(255),
                      sold boolean not null,
                      user_id int4,
                      primary key (id)
);

create table j_user (
                        id int4 generated by default as identity,
                        email varchar(255),
                        name varchar(255),
                        password varchar(255),
                        primary key (id)
);